package grupo4;

import grupo4.*;
import robocode.*;
import robocode.ScannedRobotEvent;


query "robocopca"
  accion: Accion()
end

rule "QUANDO bater na parede ENTAO SAIR"
  when
   exists HitWallEvent()
  then
    insert(new Accion(Accion.GIRAR_TANQUE_DER, 180, 1));
    insert(new Accion(Accion.AVANZAR, 30, 1));
end

rule "QUANDO nenhum robo é avistado ENTAO procurar"
  when
	  not (exists ScannedRobotEvent())
  then
	  insert (new Accion(Accion.GIRAR_RADAR_DER, 360, 1));
end

rule "QUANDO um robo inimigo é detectado ENTAO cair pra cima e mirar"
  when
    $vitima: ScannedRobotEvent($anguloRelativoVictima: bearing)
    $status: EstadoRobot()
    eval(($status.isNotTeammate($vitima.getName())))
  then
    double anguloAbsoluto = Auxiliar.anguloAbsoluto($status.getHeading(), $vitima.getBearing());
    insert(new Accion(Accion.GIRAR_TANQUE_DER, $vitima.getBearing(), 2));
    insert(new Accion(Accion.AVANZAR, 50, 2));
    double anguloRelativoCanon = Auxiliar.anguloRelativo($status.getHeading(), $status.getGunHeading());
    insert(new Accion(Accion.GIRAR_CANON_DER, ($vitima.getBearing() - anguloRelativoCanon), 2));
    double anguloRelativoRadar =  Auxiliar.anguloRelativo($status.getHeading(), $status.getRadarHeading());
    insert(new Accion(Accion.GIRAR_RADAR_DER, ($vitima.getBearing() - anguloRelativoRadar), 2));
end

rule "QUANDO um robo amigo é detectado ENTAO tentar tirar a atenção dele"
  when
    $vitima: ScannedRobotEvent($anguloRelativoVictima: bearing)
    $status: EstadoRobot()
    eval(!($status.isNotTeammate($vitima.getName())))
  then
    insert(new Accion(Accion.GIRAR_TANQUE_DER, $vitima.getBearing(), 2));
    insert(new Accion(Accion.AVANZAR, 30, 2));
    insert (new Accion(Accion.GIRAR_RADAR_DER, 360, 1));
end

rule "QUANDO é atingido ENTAO dar uma de doido"
  when
    exists HitByBulletEvent()
  then
    insert(new Accion(Accion.GIRAR_TANQUE_ESQ, $vitima.getBearing(), 1));
    insert(new Accion(Accion.AVANZAR, 50, 1));
    insert (new Accion(Accion.GIRAR_RADAR_ESQ, 360, 2));
end

rule "QUANDO acha um inimigo ENTAO atirar"
   when
      $status : EstadoRobot()
      $vitima: ScannedRobotEvent( $anguloRelativoVictima: bearing)
      eval (Math.abs($anguloRelativoVictima - Auxiliar.anguloRelativo($status.getHeading(), $status.getGunHeading())) <= 2)
   	  eval(($status.isNotTeammate($vitima.getName())))
   then
      insert(new Accion(Accion.DISPARAR, Math.min(3*(1420-$vitima.getDistance())/1420, 0.10*$status.getEnergy()), 2));
end

rule "QUANDO acertou a bala fraca e ta na mira ENTAO atirar mais forte"
  when
    exists HitRobotEvent()
    $vitima: ScannedRobotEvent( $anguloRelativoVictima: bearing)
    eval (Math.abs($anguloRelativoVictima - Auxiliar.anguloRelativo($status.getHeading(), $status.getGunHeading())) <= 2)
    eval(($status.isNotTeammate($vitima.getName())))
  then
    insert(new Accion(Accion.DISPARAR, Math.min(3*(1420-$vitima.getDistance())/1420, 0.8*$status.getEnergy()), 2));
end
